---
title: "exercise-04: wordle"
format: html
editor: visual
authors: Thi Yen Do and John Hinkle
---

## Create function 'load_dictionary()'

```{r}
load_dictionary <- function(f) {
  read.table(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE, fill = TRUE)
}
```

## Create two lists, "valid_list" and "solution_list"

```{r}
valid_list <- load_dictionary("collins-scrabble-words-2019.txt")
solution_list <- load_dictionary("google-10000-english-usa-no-swears.txt")
```

## Check that the lists contain characters

```{r}
str(valid_list)
str(solution_list)
```

## Update "solution_list" to only include words included in "valid_list" using the 'intersect()' function

```{r}
solution_list <- intersect(solution_list$words, valid_list$words)
```

## Create 'pick_solution()' function

```{r}
pick_solution <- function(solution_list, word_length = 5) {
  subset(solution_list, nchar(solution_list) == word_length) |>
  sample(size = 1)
}
```

## Create 'evaluate_guess()' function

```{r}
evaluate_guess <- function(guess, solution) {
  word_length <- length(solution)
  spaces <- rep("_", word_length)
  answer <- rep("_", word_length)
  for (i in 1:word_length) {
    if(guess[i] == solution[i]){
      spaces[i] <- "*"
      solution[i] <- "-"
    }
  }
  for (i in 1:word_length) {
    if(spaces[i] != "*"){
      x <- match(guess[i], solution)
      if(!is.na(x)) {
        spaces[i] <- "+"
        answer[x] <- "-"
      }
    }
  }
  spaces
}
```

## Create 'play_wordle()'

```{r}
play_wordle <- function(solution_list, word_length = 5, num_guesses = 6) {
  print(paste("You have", num_guesses, "chances to guess a word of length", word_length))
  print("Enter 'iquit' to quit the game and reveal the solution")
  guess_count <- 0
  solution <- pick_solution(solution_list) 
  solution_vector <- strsplit(solution, "")[[1]]
  guess_vector <- character(0)
  lettersLeft <- LETTERS
  while (num_guesses > guess_count) {
    guess_count <- guess_count + 1
    guess <- readline("Enter your guess, then press <enter>: ")
    guess_vector <- append(guess_vector, guess)
    
    if (tolower(guess) == "iquit") {
        print("You quit :|")
        break
      }
    
    while (nchar(guess) != word_length || !(toupper(guess) %in% solution_list)) {
      if (nchar(guess) != word_length) {guess <- readline(paste("Guess must be", word_length, "letters long! Try another guess:"))} 
      else if (!(toupper(guess) %in% solution_list)) {guess <- readline("This guess is not in the list of possible solutions! Try another guess:")
      }
    }
    
     guess <- toupper(guess)
     space <- strsplit(guess, "")[[1]]
     
     #evaluate guess and update keyboard
     response_vector <- evaluate_guess(space, solution_vector)
     #update keyboard
     lettersLeft <- setdiff(lettersLeft, space)
     # print result
    print(paste(strsplit(guess, "")[[1]], collapse = " "))
    print(paste(response_vector, collapse = " "))
    guess_left <- num_guesses-guess_count;
    print(paste("you have",guess_left,"guesses left"))
    print(paste(c("Letters left:", lettersLeft), collapse = " "))
    if (all(response_vector == "*")) {
      print("You won!")
      print("You guessed:")
      print(guess_vector)
      print(paste("You made", guess_count, "guesses"))
    }
  }
  print(paste("Sorry, you lost! The answer was ", solution))
  print("You guessed:")
  print(guess_vector)
  print(paste("You made", guess_count, "guesses"))
}
```

## Play Wordle

```{r}
#| echo: false
play_wordle(solution_list)
```
