---
title: "exercise-04: wordle"
format: html
editor: visual
---

## Create function load_dictionary()

```{r}
load_dictionary <- function(f) {
  read.table(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE, fill = TRUE)
}
```

## Create two variables

```{r}
valid_list <- load_dictionary("collins-scrabble-words-2019.txt")
solution_list <- load_dictionary("google-10000-english-usa-no-swears.txt")
str(valid_list)
str(solution_list)
solution_list <- as.character(solution_list)
valid_list <- as.character(valid_list)
```

## Create solution_list

```{r}
solution_list <- intersect(valid_list, solution_list)
print(solution_list)
```

## Create pick_solution()

```{r}
pick_solution <- function(solution_list, word_length = 5) {
  subset(solution_list, nchar(solution_list) == word_length)
  sample(solution_list, 1, replace = FALSE, prob = NULL)
  strsplit(solution_list, "", fixed = FALSE, perl = FALSE, useBytes = FALSE)
}
solution <- pick_solution(solution_list)
```

## Create play_wordle()

```{r}
play_wordle <- function(solution, valid_list, num_gesses = 6) {
  possibleAnswers <- solution[nchar(solution) == word_length]
  answer <- sample(solution_list, 1)
  AnswerVec <- strsplit(solution, "")
  print(paste("You have", nGusses, "chances to gues a work of length", word_length))
}
```
